export const purple = [
    {
      img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-7.jpg",
      name:"OCHENA MON",
      price:"12",
      lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      images:[
        "http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        "http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        "http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        "http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        "http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
      ]
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/06-2.jpg",
        name:"PNEORA CAHY",
        price:"15",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_03.jpg",
        name:"AROMA CAHY",
        price:"12 ",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        name:"JNOIBO AHADRE",
        price:"12",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
     
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-7.jpg",
        name:"PYARI TUMI",
        price:"12",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
  ]